import 'package:flutter/material.dart';

import 'sim_scenario.dart';

// 41 training scenarios ported from sim_training_guide.html
const List<SimScenario> simTrainingData = [
  // ── Environmental ────────────────────────────────────────────────────────────
  SimScenario(
    id: 1,
    category: 'Environmental',
    goal: 'Wind & Turbulence',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Alizol / San Carlo',
    tips: "Access via Environment Settings. Set Wind to 15 km/h and Turbulence to 20%. Practice 'crabbing' to maintain a straight path.",
    drone: 'Global (any)',
    icon: Icons.air,
  ),
  SimScenario(
    id: 2,
    category: 'Environmental',
    goal: 'Battery Simulation',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Global (Any)',
    tips: "Enable 'Realistic Power Dynamics'. Practice catching the drone at the bottom of a dive when the battery hits 3.5 V to learn thrust limitations.",
    drone: '5" Freestyle: Mark5, Apex DC5',
    icon: Icons.battery_full,
  ),
  SimScenario(
    id: 3,
    category: 'Environmental',
    goal: 'Battery Simulation',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'Global (Any)',
    tips: "Toggle 'Battery Simulation'. Use lower C-rated batteries in the workbench to force aggressive sag.",
    drone: '3.5" Cinewhoop: Cinelog35 V2',
    icon: Icons.battery_full,
  ),
  SimScenario(
    id: 4,
    category: 'Environmental',
    goal: 'Battery Simulation',
    sim: 'Liftoff: Micro Drones',
    link: 'https://store.steampowered.com/app/1432320/',
    map: 'Global (Any)',
    tips: "Select 'Authentic Mode'. Mimics rapid voltage drop of 1S batteries.",
    drone: '65mm Whoop: Air65, Mobula6',
    icon: Icons.battery_full,
  ),

  // ── Signal ────────────────────────────────────────────────────────────────────
  SimScenario(
    id: 5,
    category: 'Signal',
    goal: 'Digital Signal Simulation',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Global Settings',
    tips: 'Enable Digital Video Effects. Practice turning back the moment pixelation begins.',
    drone: 'Global (any)',
    icon: Icons.wifi,
  ),
  SimScenario(
    id: 6,
    category: 'Signal',
    goal: 'Digital Signal Simulation',
    sim: 'Liftoff: Micro Drones',
    link: 'https://store.steampowered.com/app/1432320/',
    map: 'Global Settings',
    tips: "Select 'Digital Artifacts'. Simulates HD link stutter from indoor multipath.",
    drone: 'Global (any)',
    icon: Icons.wifi,
  ),
  SimScenario(
    id: 7,
    category: 'Signal',
    goal: 'Analog Signal Simulation',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'Global Settings',
    tips: "Enable 'Analog Noise'. Learn how ghosting looks behind concrete walls.",
    drone: 'Global (any)',
    icon: Icons.wifi,
  ),
  SimScenario(
    id: 8,
    category: 'Signal',
    goal: 'Analog Signal Simulation',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Global Settings',
    tips: 'Enable Analog Simulation. Put high objects between you and the spawn point.',
    drone: 'Global (any)',
    icon: Icons.wifi,
  ),

  // ── Technical ─────────────────────────────────────────────────────────────────
  SimScenario(
    id: 9,
    category: 'Technical',
    goal: 'Interior House Tours',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: "Joshua Bardwell's House",
    tips: 'Master the garage-to-kitchen line. Focus on lighting transitions.',
    drone: '2" Cinewhoop: Pavo20 Pro',
    icon: Icons.home_rounded,
  ),
  SimScenario(
    id: 32,
    category: 'Technical',
    goal: 'Interior House Tours',
    sim: 'FPV Logic',
    link: 'https://store.steampowered.com/app/2398030/',
    map: 'Suburbs / Neighborhood',
    tips: 'The gold standard for real estate practice. Multiple fully furnished houses with diverse layouts. Practice room-to-room transitions and exterior flow.',
    drone: '2" - 3" Cinewhoop: Pavo25 V2',
    icon: Icons.home_rounded,
  ),
  SimScenario(
    id: 10,
    category: 'Technical',
    goal: 'Interior House Tours',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Real Spots (Bardwell House)',
    tips: 'UE5 version with realistic shadows. Focus on smooth cinematic movements.',
    drone: 'Sub-250g: QAV-S 2 SE',
    icon: Icons.home_rounded,
  ),
  SimScenario(
    id: 11,
    category: 'Technical',
    goal: 'Interior House Tours',
    sim: 'Liftoff: Micro Drones',
    link: 'https://store.steampowered.com/app/1432320/',
    map: 'The Apartment',
    tips: "Fly under tables to feel the 'ground effect' suction.",
    drone: '65mm Whoop: Mobula6 2024',
    icon: Icons.sports_esports_rounded,
  ),
  SimScenario(
    id: 25,
    category: 'Technical',
    goal: 'Commercial / Industrial Tours',
    sim: 'FPV Logic',
    link: 'https://store.steampowered.com/app/2398030/',
    map: 'Factory 1 & 2',
    tips: 'Consistent cinemapping through complex structures. Focus on pipe proximity.',
    drone: '3.5" Cinematic or 5" Cine',
    icon: Icons.business,
  ),
  SimScenario(
    id: 26,
    category: 'Technical',
    goal: 'Commercial / Industrial Tours',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Industrial Warehouse',
    tips: 'Navigate catwalks and vertical shelving for inspection practice.',
    drone: '3" to 5" Cinewhoop',
    icon: Icons.business,
  ),
  SimScenario(
    id: 27,
    category: 'Technical',
    goal: 'Commercial / Industrial Tours',
    sim: 'Liftoff: Micro Drones',
    link: 'https://store.steampowered.com/app/1432320/',
    map: 'Office / Workspace',
    tips: 'Master tight throttle management for retail or office tours.',
    drone: '65mm – 75mm Whoop',
    icon: Icons.work,
  ),
  SimScenario(
    id: 12,
    category: 'Technical',
    goal: 'Freestyle & Bandos',
    sim: 'FPV Logic',
    link: 'https://store.steampowered.com/app/2398030/',
    map: 'Factory 1 / Factory 2',
    tips: 'High-density gaps with raw physics feel. Rewards Matty Flips.',
    drone: '5" Freestyle: SpeedyBee Bee35',
    icon: Icons.business,
  ),
  SimScenario(
    id: 13,
    category: 'Technical',
    goal: 'Freestyle & Bandos',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'The Bando',
    tips: 'Practice technical gaps and throttle timing on power loops.',
    drone: '5" Freestyle: Armattan Badger',
    icon: Icons.business,
  ),
  SimScenario(
    id: 28,
    category: 'Technical',
    goal: 'Freestyle & Bandos',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Abandoned Factory',
    tips: 'High-speed rock-rubbing and proximity trick correction.',
    drone: '5" Freestyle: Mark5, Apex DC5',
    icon: Icons.business,
  ),
  SimScenario(
    id: 29,
    category: 'Technical',
    goal: 'Freestyle & Bandos',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'San Carlo (Urban Ruins)',
    tips: 'Flow from skyscrapers directly into technical street freestyle.',
    drone: '5" Cinematic / Freestyle',
    icon: Icons.business,
  ),
  SimScenario(
    id: 30,
    category: 'Technical',
    goal: 'Freestyle & Bandos',
    sim: 'VelociDrone',
    link: 'https://www.velocidrone.com/',
    map: 'Industrial Wasteland',
    tips: 'Low-latency environment. Best for high-precision input lines.',
    drone: '5" Freestyle: ImpulseRC Apex',
    icon: Icons.business,
  ),

  // ── Automotive ────────────────────────────────────────────────────────────────
  SimScenario(
    id: 33,
    category: 'Automotive',
    goal: 'Filming Cars: Race Track',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Race Track',
    tips: 'Maintain distance from the lead car while matching their racing line. Focus on corner apex transitions.',
    drone: '5" Speed: iFlight Mach R5',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 34,
    category: 'Automotive',
    goal: 'Filming Cars: Race Track',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'Slipstream DLC Tracks',
    tips: 'Use the Slipstream physics to track high-speed vehicles. Practice diving into the corkscrew behind a car.',
    drone: '5" Freestyle: Mark5',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 35,
    category: 'Automotive',
    goal: 'Filming Cars: Drifting',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Parking Lot / Drift Track',
    tips: "Proximity is key. Keep the drone steady near the driver-side door during a slide.",
    drone: '5" Freestyle: Apex DC5',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 36,
    category: 'Automotive',
    goal: 'Filming Cars: Drifting',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'Slipstream Drift Scene',
    tips: "Coordinate your yaw with the car's rotation. Use the 'Chase' camera settings to verify framing.",
    drone: '5" Cinematic: AOS 5',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 37,
    category: 'Automotive',
    goal: 'Filming Cars: Slow Driving',
    sim: 'Liftoff',
    link: 'https://store.steampowered.com/app/441830/',
    map: 'Slipstream Mountain (Pickup)',
    tips: "Practice orbiting a slow-moving truck on a cliffside. Focus on 'creeping' throttle management.",
    drone: '3.5" Cinewhoop: Cinelog35',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 38,
    category: 'Automotive',
    goal: 'Filming Cars: Rally',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Rally Stage',
    tips: 'Follow cars through tight forest bends. Predict jumps to capture the best air-time angle.',
    drone: '5" Freestyle: SpeedyBee Bee35',
    icon: Icons.directions_car,
  ),
  SimScenario(
    id: 39,
    category: 'Automotive',
    goal: 'Filming Cars: Offroad',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'Desert Map',
    tips: 'Chase offroad rigs across dunes. Practice tracking at a 3/4 angle to show vehicle suspension work.',
    drone: '7" Long Range: Chimera7',
    icon: Icons.directions_car,
  ),

  // ── Extreme Sports ────────────────────────────────────────────────────────────
  SimScenario(
    id: 40,
    category: 'Extreme Sports',
    goal: 'Extreme Sports: Wingsuit',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Alizol (Mountain Peaks)',
    tips: 'High-speed pursuit. Set camera tilt to 50°+ to track the extreme glide ratio. Maintain a consistent offset to avoid prop wash.',
    drone: '5" or 7" Cinematic',
    icon: Icons.electric_bolt,
  ),
  SimScenario(
    id: 41,
    category: 'Extreme Sports',
    goal: 'Extreme Sports: Ski and Snowboard',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Snow Odyssey',
    tips: 'Low-altitude tracking. Emphasize speed by flying inches above the snow. Watch for rapid changes in rider direction at gates.',
    drone: '5" Cinematic: AOS 5',
    icon: Icons.terrain,
  ),
  SimScenario(
    id: 42,
    category: 'Extreme Sports',
    goal: 'Extreme Sports: Ski Jump',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Snow Odyssey',
    tips: "Coordinate the launch. Match the athlete's speed on the ramp and practice an 'arc' orbit as they transition into flight.",
    drone: '5" Freestyle',
    icon: Icons.trending_up,
  ),
  SimScenario(
    id: 43,
    category: 'Extreme Sports',
    goal: 'Extreme Sports: Base Jumping and Skydiving',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Alizol',
    tips: "Vertical diving. Master the weightless 'catch' as you match the jumper's freefall acceleration.",
    drone: '5" Cinematic',
    icon: Icons.anchor,
  ),

  // ── Aviation ──────────────────────────────────────────────────────────────────
  SimScenario(
    id: 44,
    category: 'Aviation',
    goal: 'Filming Airplanes',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'San Carlo (Airport)',
    tips: 'Large scale tracking. Track planes during landing or takeoff. Use 7" rigs for the stability required for these massive subjects.',
    drone: '7" Long Range: Chimera7',
    icon: Icons.flight,
  ),

  // ── Racing ────────────────────────────────────────────────────────────────────
  SimScenario(
    id: 14,
    category: 'Racing',
    goal: 'Pro Drone Racing',
    sim: 'VelociDrone',
    link: 'https://www.velocidrone.com/',
    map: 'Empty Scene (MultiGP)',
    tips: 'Official MultiGP tracks. The standard for racing muscle memory.',
    drone: '5" Racing: Five33 LightSwitch v2',
    icon: Icons.flag,
  ),
  SimScenario(
    id: 31,
    category: 'Racing',
    goal: 'Pro Drone Racing',
    sim: 'DRL Simulator',
    link: 'https://store.steampowered.com/app/641780/',
    map: 'The Gates of Hell / DRL Tracks',
    tips: 'The standard for DRL league hopefuls. Practice the physics-heavy gates of official Season tracks to master high-speed momentum.',
    drone: '5" Racing: DRL Racer4',
    icon: Icons.flag,
  ),

  // ── Scale ─────────────────────────────────────────────────────────────────────
  SimScenario(
    id: 16,
    category: 'Scale',
    goal: 'Mountain Surfing',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Alizol / Snow Odyssey',
    tips: 'Ridge-running across 4km maps. Master LoS signal maintenance.',
    drone: '7" Long Range: Chimera7, Explorer LR',
    icon: Icons.terrain,
  ),
  SimScenario(
    id: 18,
    category: 'Scale',
    goal: 'Skyscraper Dives',
    sim: 'DRL Simulator',
    link: 'https://store.steampowered.com/app/641780/',
    map: 'LApocalypse',
    tips: 'Increase Weight Slider to stop floaty feeling on catch.',
    drone: '5" Racing: DRL Racer4',
    icon: Icons.business,
  ),
  SimScenario(
    id: 19,
    category: 'Scale',
    goal: 'Skyscraper Dives',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'San Carlo (City Center)',
    tips: 'High-fidelity vertical drops and lighting transitions.',
    drone: '5" Cinematic: AOS 5, Bob5',
    icon: Icons.business,
  ),

  // ── Dynamic ───────────────────────────────────────────────────────────────────
  SimScenario(
    id: 20,
    category: 'Dynamic',
    goal: 'Filming and landing on moving boats',
    sim: 'Uncrashed',
    link: 'https://store.steampowered.com/app/1682970/',
    map: 'High City Port',
    tips: 'Match speed from stern at 45°. Wires/mast have active hitboxes.',
    drone: '5" Freestyle: Mark5, Apex DC5',
    icon: Icons.directions_boat,
  ),
  SimScenario(
    id: 21,
    category: 'Dynamic',
    goal: 'Filming and landing on moving boats',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'San Carlo (Lake)',
    tips: 'Track motorboats. Practice orbits then descend for deck landing.',
    drone: '7" Cinematic: Helion10',
    icon: Icons.anchor,
  ),
  SimScenario(
    id: 22,
    category: 'Dynamic',
    goal: 'Motocross / Bike Chasing',
    sim: 'TRYP FPV',
    link: 'https://store.steampowered.com/app/1881200/',
    map: 'Alizol (TRYP Mode)',
    tips: 'Set AI speed to 1.5x. Practice centered framing on jumps.',
    drone: '5" Speed: iFlight Mach R5',
    icon: Icons.navigation,
  ),

  // ── Drone Warfare ─────────────────────────────────────────────────────────────
  SimScenario(
    id: 24,
    category: 'Drone Warfare',
    goal: 'Drone Warfare',
    sim: 'FPV Kamikaze Drone',
    link: 'https://store.steampowered.com/app/2330770/',
    map: 'Trench Wasteland',
    tips: 'Stay below trench lip to avoid AI line-of-sight.',
    drone: '10" Heavy: Custom 10" Rig',
    icon: Icons.gps_fixed,
  ),
];
